#
# docker-compose for dev
# ... opens port 4300
#
version: "3"

services:
    nginx:
      image: richarvey/nginx-php-fpm:latest
      container_name: cometa_website
      restart: always
      volumes:
        - ./:/cometa_website
      working_dir: /cometa_website
      environment:
        - PHP_ERRORS_STDERR=TRUE
      ports:
        - "8011:80"
        # use port 4300 ... as other projects like cometa_front run on 4200
        - "4300:4300"

      command: bash -c "./prepare.sh full
          && echo forking ng serve
          && ./prepare.sh serve"