#
# docker-compose for dev
# ... opens port 4300
#
version: "3"

services:
    nginx:
      # take an image that supports php
      image: richarvey/nginx-php-fpm:latest
      container_name: cometa_web_v3
      restart: always
      volumes:
        # mount working_dir for docker-compose
        - ./:/cometa_website
        # mount configuration for nginx 
        - ./default_dev.conf:/etc/nginx/conf.d/default.conf
        - ./default_dev.conf:/etc/nginx/sites-available/default.conf
        # mount dist/cometa-rocks-website to html-root of nginx
        # - ./dist/cometa-rocks-website:/var/www/html
        # mount php direcotry to be available to nginx inside document root
        - ./php:/var/www/html/php
        - /etc/timezone:/etc/TZ
      working_dir: /cometa_website
      environment:
        - PHP_ERRORS_STDERR=TRUE
      ports:
        - "8011:80"
        # use port 4300 ... as other projects like cometa_front run on 4200
        - "4300:4300"

      command: bash -c "./prepare.sh full
        && echo forking ng serve
        && ./prepare.sh serve"